language: python

python:
  - "2.7"

env:
    global:
        - DEPENDS="nose"

install:
  - pip install $DEPENDS
  - pip install -e .

matrix:
  include:
    - python: 2.7
    - python: 2.7
      env:
        - DEPENDS="pydicom==0.9.9"

script: 
  - nosetests -v
